// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"database/sql"
)

const approveUser = `-- name: ApproveUser :exec
UPDATE users SET approved = 1, franchise_id = ? WHERE id = ?
`

type ApproveUserParams struct {
	FranchiseID sql.NullInt64 `json:"franchise_id"`
	ID          int64         `json:"id"`
}

func (q *Queries) ApproveUser(ctx context.Context, arg ApproveUserParams) error {
	_, err := q.db.ExecContext(ctx, approveUser, arg.FranchiseID, arg.ID)
	return err
}

const createApprovedEmail = `-- name: CreateApprovedEmail :exec
INSERT INTO approved_emails (email, franchise_id) VALUES (?, ?)
ON CONFLICT(email) DO UPDATE SET franchise_id = excluded.franchise_id
`

type CreateApprovedEmailParams struct {
	Email       string `json:"email"`
	FranchiseID int64  `json:"franchise_id"`
}

func (q *Queries) CreateApprovedEmail(ctx context.Context, arg CreateApprovedEmailParams) error {
	_, err := q.db.ExecContext(ctx, createApprovedEmail, arg.Email, arg.FranchiseID)
	return err
}

const createFranchise = `-- name: CreateFranchise :exec
INSERT INTO franchises (name) VALUES (?)
`

func (q *Queries) CreateFranchise(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createFranchise, name)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, franchise_id, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID          string        `json:"id"`
	UserID      int64         `json:"user_id"`
	FranchiseID sql.NullInt64 `json:"franchise_id"`
	ExpiresAt   string        `json:"expires_at"`
}

// Sessions --------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.FranchiseID,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (google_id, email, name, picture_url) VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	GoogleID   string `json:"google_id"`
	Email      string `json:"email"`
	Name       string `json:"name"`
	PictureUrl string `json:"picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	return err
}

const deleteApprovedEmail = `-- name: DeleteApprovedEmail :exec
DELETE FROM approved_emails WHERE email = ?
`

func (q *Queries) DeleteApprovedEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteApprovedEmail, email)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getApprovedEmail = `-- name: GetApprovedEmail :one

SELECT email, franchise_id FROM approved_emails WHERE email = ?
`

// Approved emails -------------------------------------------------------
func (q *Queries) GetApprovedEmail(ctx context.Context, email string) (ApprovedEmail, error) {
	row := q.db.QueryRowContext(ctx, getApprovedEmail, email)
	var i ApprovedEmail
	err := row.Scan(&i.Email, &i.FranchiseID)
	return i, err
}

const getFranchise = `-- name: GetFranchise :one

SELECT id, name, active, created_at FROM franchises WHERE id = ?
`

// Franchises ------------------------------------------------------------
func (q *Queries) GetFranchise(ctx context.Context, id int64) (Franchise, error) {
	row := q.db.QueryRowContext(ctx, getFranchise, id)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getFranchiseByName = `-- name: GetFranchiseByName :one
SELECT id, name, active, created_at FROM franchises WHERE name = ?
`

func (q *Queries) GetFranchiseByName(ctx context.Context, name string) (Franchise, error) {
	row := q.db.QueryRowContext(ctx, getFranchiseByName, name)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getLastFranchise = `-- name: GetLastFranchise :one
SELECT id, name, active, created_at FROM franchises WHERE id = (SELECT MAX(id) FROM franchises)
`

func (q *Queries) GetLastFranchise(ctx context.Context) (Franchise, error) {
	row := q.db.QueryRowContext(ctx, getLastFranchise)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, franchise_id, expires_at FROM sessions WHERE id = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FranchiseID,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one

SELECT id, google_id, email, name, picture_url, franchise_id, is_admin, approved, created_at FROM users WHERE google_id = ?
`

// Users -----------------------------------------------------------------
func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.FranchiseID,
		&i.IsAdmin,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, name, picture_url, franchise_id, is_admin, approved, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.FranchiseID,
		&i.IsAdmin,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedEmails = `-- name: ListApprovedEmails :many
SELECT a.email, a.franchise_id, f.name AS franchise_name
FROM approved_emails a
JOIN franchises f ON f.id = a.franchise_id
ORDER BY a.email
`

type ListApprovedEmailsRow struct {
	Email         string `json:"email"`
	FranchiseID   int64  `json:"franchise_id"`
	FranchiseName string `json:"franchise_name"`
}

func (q *Queries) ListApprovedEmails(ctx context.Context) ([]ListApprovedEmailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedEmailsRow
	for rows.Next() {
		var i ListApprovedEmailsRow
		if err := rows.Scan(&i.Email, &i.FranchiseID, &i.FranchiseName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFranchises = `-- name: ListFranchises :many
SELECT id, name, active, created_at FROM franchises WHERE active = 1 ORDER BY name
`

func (q *Queries) ListFranchises(ctx context.Context) ([]Franchise, error) {
	rows, err := q.db.QueryContext(ctx, listFranchises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Franchise
	for rows.Next() {
		var i Franchise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, google_id, email, name, picture_url, franchise_id, is_admin, approved, created_at FROM users WHERE approved = 0 ORDER BY created_at DESC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Name,
			&i.PictureUrl,
			&i.FranchiseID,
			&i.IsAdmin,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.google_id, u.email, u.name, u.picture_url, u.franchise_id, u.is_admin, u.approved, u.created_at, f.name AS franchise_name
FROM users u
LEFT JOIN franchises f ON f.id = u.franchise_id
ORDER BY u.approved DESC, u.name
`

type ListUsersRow struct {
	ID            int64          `json:"id"`
	GoogleID      string         `json:"google_id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	PictureUrl    string         `json:"picture_url"`
	FranchiseID   sql.NullInt64  `json:"franchise_id"`
	IsAdmin       int64          `json:"is_admin"`
	Approved      int64          `json:"approved"`
	CreatedAt     string         `json:"created_at"`
	FranchiseName sql.NullString `json:"franchise_name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Name,
			&i.PictureUrl,
			&i.FranchiseID,
			&i.IsAdmin,
			&i.Approved,
			&i.CreatedAt,
			&i.FranchiseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeUserAdmin = `-- name: MakeUserAdmin :exec
UPDATE users SET is_admin = 1, approved = 1, franchise_id = NULL WHERE id = ?
`

func (q *Queries) MakeUserAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, makeUserAdmin, id)
	return err
}

const setSessionFranchise = `-- name: SetSessionFranchise :exec
UPDATE sessions SET franchise_id = ? WHERE id = ?
`

type SetSessionFranchiseParams struct {
	FranchiseID sql.NullInt64 `json:"franchise_id"`
	ID          string        `json:"id"`
}

func (q *Queries) SetSessionFranchise(ctx context.Context, arg SetSessionFranchiseParams) error {
	_, err := q.db.ExecContext(ctx, setSessionFranchise, arg.FranchiseID, arg.ID)
	return err
}

const updateFranchiseName = `-- name: UpdateFranchiseName :exec
UPDATE franchises SET name = ? WHERE id = ?
`

type UpdateFranchiseNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateFranchiseName(ctx context.Context, arg UpdateFranchiseNameParams) error {
	_, err := q.db.ExecContext(ctx, updateFranchiseName, arg.Name, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name = ?, picture_url = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Name       string `json:"name"`
	PictureUrl string `json:"picture_url"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Name, arg.PictureUrl, arg.ID)
	return err
}
