// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"database/sql"
)

const assignCustomerToRun = `-- name: AssignCustomerToRun :exec
UPDATE customers SET run_id = ?,
    sort_order = (SELECT COALESCE(MAX(c2.sort_order), 0) + 1 FROM customers c2 WHERE c2.run_id = ?)
WHERE customers.id = ?
`

type AssignCustomerToRunParams struct {
	RunID   sql.NullInt64 `json:"run_id"`
	RunID_2 sql.NullInt64 `json:"run_id_2"`
	ID      int64         `json:"id"`
}

func (q *Queries) AssignCustomerToRun(ctx context.Context, arg AssignCustomerToRunParams) error {
	_, err := q.db.ExecContext(ctx, assignCustomerToRun, arg.RunID, arg.RunID_2, arg.ID)
	return err
}

const createContact = `-- name: CreateContact :exec
INSERT INTO contacts (customer_id, name, role, is_primary, phone) VALUES (?, ?, ?, ?, ?)
`

type CreateContactParams struct {
	CustomerID int64  `json:"customer_id"`
	Name       string `json:"name"`
	Role       string `json:"role"`
	IsPrimary  int64  `json:"is_primary"`
	Phone      string `json:"phone"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) error {
	_, err := q.db.ExecContext(ctx, createContact,
		arg.CustomerID,
		arg.Name,
		arg.Role,
		arg.IsPrimary,
		arg.Phone,
	)
	return err
}

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO customers (franchise_id, run_id, sort_order, name)
VALUES (?, ?, (SELECT COALESCE(MAX(c2.sort_order), 0) + 1 FROM customers c2 WHERE c2.run_id = ?), ?)
`

type CreateCustomerParams struct {
	FranchiseID int64         `json:"franchise_id"`
	RunID       sql.NullInt64 `json:"run_id"`
	RunID_2     sql.NullInt64 `json:"run_id_2"`
	Name        string        `json:"name"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, createCustomer,
		arg.FranchiseID,
		arg.RunID,
		arg.RunID_2,
		arg.Name,
	)
	return err
}

const createDispenser = `-- name: CreateDispenser :exec
INSERT INTO dispensers (customer_id, zone_id, sort_order, seq_label, location,
    model_id, quantity, fragrance_id, fragrance_note, refill_size_ml,
    service_interval_days, notes)
VALUES (?, ?, (SELECT COALESCE(MAX(d2.sort_order), 0) + 1 FROM dispensers d2 WHERE d2.customer_id = ?),
    ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDispenserParams struct {
	CustomerID          int64         `json:"customer_id"`
	ZoneID              sql.NullInt64 `json:"zone_id"`
	CustomerID_2        int64         `json:"customer_id_2"`
	SeqLabel            string        `json:"seq_label"`
	Location            string        `json:"location"`
	ModelID             int64         `json:"model_id"`
	Quantity            int64         `json:"quantity"`
	FragranceID         sql.NullInt64 `json:"fragrance_id"`
	FragranceNote       string        `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64 `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64 `json:"service_interval_days"`
	Notes               string        `json:"notes"`
}

func (q *Queries) CreateDispenser(ctx context.Context, arg CreateDispenserParams) error {
	_, err := q.db.ExecContext(ctx, createDispenser,
		arg.CustomerID,
		arg.ZoneID,
		arg.CustomerID_2,
		arg.SeqLabel,
		arg.Location,
		arg.ModelID,
		arg.Quantity,
		arg.FragranceID,
		arg.FragranceNote,
		arg.RefillSizeMl,
		arg.ServiceIntervalDays,
		arg.Notes,
	)
	return err
}

const createZone = `-- name: CreateZone :exec
INSERT INTO zones (customer_id, sort_order, label, area)
VALUES (?, (SELECT COALESCE(MAX(z2.sort_order), 0) + 1 FROM zones z2 WHERE z2.customer_id = ?), ?, ?)
`

type CreateZoneParams struct {
	CustomerID   int64  `json:"customer_id"`
	CustomerID_2 int64  `json:"customer_id_2"`
	Label        string `json:"label"`
	Area         string `json:"area"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) error {
	_, err := q.db.ExecContext(ctx, createZone,
		arg.CustomerID,
		arg.CustomerID_2,
		arg.Label,
		arg.Area,
	)
	return err
}

const customerModelTally = `-- name: CustomerModelTally :many
SELECT m.name AS model_name, CAST(SUM(d.quantity) AS INTEGER) AS units
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
WHERE d.customer_id = ? AND d.active = 1
GROUP BY m.id
ORDER BY units DESC, m.name
`

type CustomerModelTallyRow struct {
	ModelName string `json:"model_name"`
	Units     int64  `json:"units"`
}

func (q *Queries) CustomerModelTally(ctx context.Context, customerID int64) ([]CustomerModelTallyRow, error) {
	rows, err := q.db.QueryContext(ctx, customerModelTally, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerModelTallyRow
	for rows.Next() {
		var i CustomerModelTallyRow
		if err := rows.Scan(&i.ModelName, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateCustomer = `-- name: DeactivateCustomer :exec
UPDATE customers SET active = 0, run_id = NULL WHERE id = ?
`

func (q *Queries) DeactivateCustomer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateCustomer, id)
	return err
}

const deactivateDispenser = `-- name: DeactivateDispenser :exec
UPDATE dispensers SET active = 0 WHERE id = ?
`

func (q *Queries) DeactivateDispenser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateDispenser, id)
	return err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = ?
`

func (q *Queries) DeleteContact(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContact, id)
	return err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = ?
`

func (q *Queries) DeleteZone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, customer_id, name, role, is_primary, phone, notes FROM contacts WHERE id = ?
`

func (q *Queries) GetContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Role,
		&i.IsPrimary,
		&i.Phone,
		&i.Notes,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, franchise_id, run_id, sort_order, name, address_line, suburb, phone, map_ref, regarding, service_minutes, access_notes, general_notes, active FROM customers WHERE id = ?
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.RunID,
		&i.SortOrder,
		&i.Name,
		&i.AddressLine,
		&i.Suburb,
		&i.Phone,
		&i.MapRef,
		&i.Regarding,
		&i.ServiceMinutes,
		&i.AccessNotes,
		&i.GeneralNotes,
		&i.Active,
	)
	return i, err
}

const getDispenser = `-- name: GetDispenser :one
SELECT d.id, d.customer_id, d.zone_id, d.sort_order, d.seq_label, d.location, d.model_id, d.quantity, d.fragrance_id, d.fragrance_note, d.refill_size_ml, d.service_interval_days, d.notes, d.active, m.name AS model_name, f.name AS fragrance_name
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
LEFT JOIN fragrances f ON f.id = d.fragrance_id
WHERE d.id = ?
`

type GetDispenserRow struct {
	ID                  int64          `json:"id"`
	CustomerID          int64          `json:"customer_id"`
	ZoneID              sql.NullInt64  `json:"zone_id"`
	SortOrder           int64          `json:"sort_order"`
	SeqLabel            string         `json:"seq_label"`
	Location            string         `json:"location"`
	ModelID             int64          `json:"model_id"`
	Quantity            int64          `json:"quantity"`
	FragranceID         sql.NullInt64  `json:"fragrance_id"`
	FragranceNote       string         `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64  `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64  `json:"service_interval_days"`
	Notes               string         `json:"notes"`
	Active              int64          `json:"active"`
	ModelName           string         `json:"model_name"`
	FragranceName       sql.NullString `json:"fragrance_name"`
}

func (q *Queries) GetDispenser(ctx context.Context, id int64) (GetDispenserRow, error) {
	row := q.db.QueryRowContext(ctx, getDispenser, id)
	var i GetDispenserRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ZoneID,
		&i.SortOrder,
		&i.SeqLabel,
		&i.Location,
		&i.ModelID,
		&i.Quantity,
		&i.FragranceID,
		&i.FragranceNote,
		&i.RefillSizeMl,
		&i.ServiceIntervalDays,
		&i.Notes,
		&i.Active,
		&i.ModelName,
		&i.FragranceName,
	)
	return i, err
}

const getLastContact = `-- name: GetLastContact :one
SELECT id, customer_id, name, role, is_primary, phone, notes FROM contacts WHERE id = (SELECT MAX(id) FROM contacts)
`

func (q *Queries) GetLastContact(ctx context.Context) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getLastContact)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Role,
		&i.IsPrimary,
		&i.Phone,
		&i.Notes,
	)
	return i, err
}

const getLastCustomer = `-- name: GetLastCustomer :one
SELECT id, franchise_id, run_id, sort_order, name, address_line, suburb, phone, map_ref, regarding, service_minutes, access_notes, general_notes, active FROM customers WHERE id = (SELECT MAX(id) FROM customers)
`

func (q *Queries) GetLastCustomer(ctx context.Context) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getLastCustomer)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.RunID,
		&i.SortOrder,
		&i.Name,
		&i.AddressLine,
		&i.Suburb,
		&i.Phone,
		&i.MapRef,
		&i.Regarding,
		&i.ServiceMinutes,
		&i.AccessNotes,
		&i.GeneralNotes,
		&i.Active,
	)
	return i, err
}

const getLastDispenser = `-- name: GetLastDispenser :one
SELECT d.id, d.customer_id, d.zone_id, d.sort_order, d.seq_label, d.location, d.model_id, d.quantity, d.fragrance_id, d.fragrance_note, d.refill_size_ml, d.service_interval_days, d.notes, d.active, m.name AS model_name, f.name AS fragrance_name
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
LEFT JOIN fragrances f ON f.id = d.fragrance_id
WHERE d.id = (SELECT MAX(id) FROM dispensers)
`

type GetLastDispenserRow struct {
	ID                  int64          `json:"id"`
	CustomerID          int64          `json:"customer_id"`
	ZoneID              sql.NullInt64  `json:"zone_id"`
	SortOrder           int64          `json:"sort_order"`
	SeqLabel            string         `json:"seq_label"`
	Location            string         `json:"location"`
	ModelID             int64          `json:"model_id"`
	Quantity            int64          `json:"quantity"`
	FragranceID         sql.NullInt64  `json:"fragrance_id"`
	FragranceNote       string         `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64  `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64  `json:"service_interval_days"`
	Notes               string         `json:"notes"`
	Active              int64          `json:"active"`
	ModelName           string         `json:"model_name"`
	FragranceName       sql.NullString `json:"fragrance_name"`
}

func (q *Queries) GetLastDispenser(ctx context.Context) (GetLastDispenserRow, error) {
	row := q.db.QueryRowContext(ctx, getLastDispenser)
	var i GetLastDispenserRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ZoneID,
		&i.SortOrder,
		&i.SeqLabel,
		&i.Location,
		&i.ModelID,
		&i.Quantity,
		&i.FragranceID,
		&i.FragranceNote,
		&i.RefillSizeMl,
		&i.ServiceIntervalDays,
		&i.Notes,
		&i.Active,
		&i.ModelName,
		&i.FragranceName,
	)
	return i, err
}

const getLastZone = `-- name: GetLastZone :one
SELECT id, customer_id, sort_order, label, area, access_notes, notes FROM zones WHERE id = (SELECT MAX(id) FROM zones)
`

func (q *Queries) GetLastZone(ctx context.Context) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getLastZone)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SortOrder,
		&i.Label,
		&i.Area,
		&i.AccessNotes,
		&i.Notes,
	)
	return i, err
}

const getZone = `-- name: GetZone :one
SELECT id, customer_id, sort_order, label, area, access_notes, notes FROM zones WHERE id = ?
`

func (q *Queries) GetZone(ctx context.Context, id int64) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SortOrder,
		&i.Label,
		&i.Area,
		&i.AccessNotes,
		&i.Notes,
	)
	return i, err
}

const getZoneByLabel = `-- name: GetZoneByLabel :one
SELECT id, customer_id, sort_order, label, area, access_notes, notes FROM zones WHERE customer_id = ? AND label = ? COLLATE NOCASE LIMIT 1
`

type GetZoneByLabelParams struct {
	CustomerID int64  `json:"customer_id"`
	Label      string `json:"label"`
}

func (q *Queries) GetZoneByLabel(ctx context.Context, arg GetZoneByLabelParams) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getZoneByLabel, arg.CustomerID, arg.Label)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SortOrder,
		&i.Label,
		&i.Area,
		&i.AccessNotes,
		&i.Notes,
	)
	return i, err
}

const listContactsByCustomer = `-- name: ListContactsByCustomer :many

SELECT id, customer_id, name, role, is_primary, phone, notes FROM contacts WHERE customer_id = ? ORDER BY is_primary DESC, id
`

// Contacts --------------------------------------------------------------
func (q *Queries) ListContactsByCustomer(ctx context.Context, customerID int64) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.Role,
			&i.IsPrimary,
			&i.Phone,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByFranchise = `-- name: ListCustomersByFranchise :many

SELECT c.id, c.franchise_id, c.run_id, c.sort_order, c.name, c.address_line, c.suburb, c.phone, c.map_ref, c.regarding, c.service_minutes, c.access_notes, c.general_notes, c.active, r.name AS run_name,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     WHERE d.customer_id = c.id AND d.active = 1) AS unit_count
FROM customers c
LEFT JOIN runs r ON r.id = c.run_id
WHERE c.franchise_id = ? AND c.active = 1
  AND (? = '' OR c.name LIKE ? OR c.suburb LIKE ?)
ORDER BY c.name
`

type ListCustomersByFranchiseParams struct {
	FranchiseID int64       `json:"franchise_id"`
	Column2     interface{} `json:"column_2"`
	Name        string      `json:"name"`
	Suburb      string      `json:"suburb"`
}

type ListCustomersByFranchiseRow struct {
	ID             int64          `json:"id"`
	FranchiseID    int64          `json:"franchise_id"`
	RunID          sql.NullInt64  `json:"run_id"`
	SortOrder      int64          `json:"sort_order"`
	Name           string         `json:"name"`
	AddressLine    string         `json:"address_line"`
	Suburb         string         `json:"suburb"`
	Phone          string         `json:"phone"`
	MapRef         string         `json:"map_ref"`
	Regarding      string         `json:"regarding"`
	ServiceMinutes int64          `json:"service_minutes"`
	AccessNotes    string         `json:"access_notes"`
	GeneralNotes   string         `json:"general_notes"`
	Active         int64          `json:"active"`
	RunName        sql.NullString `json:"run_name"`
	UnitCount      int64          `json:"unit_count"`
}

// Customers -----------------------------------------------------------------
func (q *Queries) ListCustomersByFranchise(ctx context.Context, arg ListCustomersByFranchiseParams) ([]ListCustomersByFranchiseRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersByFranchise,
		arg.FranchiseID,
		arg.Column2,
		arg.Name,
		arg.Suburb,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersByFranchiseRow
	for rows.Next() {
		var i ListCustomersByFranchiseRow
		if err := rows.Scan(
			&i.ID,
			&i.FranchiseID,
			&i.RunID,
			&i.SortOrder,
			&i.Name,
			&i.AddressLine,
			&i.Suburb,
			&i.Phone,
			&i.MapRef,
			&i.Regarding,
			&i.ServiceMinutes,
			&i.AccessNotes,
			&i.GeneralNotes,
			&i.Active,
			&i.RunName,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispensersByCustomer = `-- name: ListDispensersByCustomer :many

SELECT d.id, d.customer_id, d.zone_id, d.sort_order, d.seq_label, d.location, d.model_id, d.quantity, d.fragrance_id, d.fragrance_note, d.refill_size_ml, d.service_interval_days, d.notes, d.active, m.name AS model_name, f.name AS fragrance_name,
    z.label AS zone_label, z.area AS zone_area, z.sort_order AS zone_sort
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
LEFT JOIN fragrances f ON f.id = d.fragrance_id
LEFT JOIN zones z ON z.id = d.zone_id
WHERE d.customer_id = ? AND d.active = 1
ORDER BY COALESCE(z.sort_order, 999999), d.sort_order, d.id
`

type ListDispensersByCustomerRow struct {
	ID                  int64          `json:"id"`
	CustomerID          int64          `json:"customer_id"`
	ZoneID              sql.NullInt64  `json:"zone_id"`
	SortOrder           int64          `json:"sort_order"`
	SeqLabel            string         `json:"seq_label"`
	Location            string         `json:"location"`
	ModelID             int64          `json:"model_id"`
	Quantity            int64          `json:"quantity"`
	FragranceID         sql.NullInt64  `json:"fragrance_id"`
	FragranceNote       string         `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64  `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64  `json:"service_interval_days"`
	Notes               string         `json:"notes"`
	Active              int64          `json:"active"`
	ModelName           string         `json:"model_name"`
	FragranceName       sql.NullString `json:"fragrance_name"`
	ZoneLabel           sql.NullString `json:"zone_label"`
	ZoneArea            sql.NullString `json:"zone_area"`
	ZoneSort            sql.NullInt64  `json:"zone_sort"`
}

// Dispensers ------------------------------------------------------------
func (q *Queries) ListDispensersByCustomer(ctx context.Context, customerID int64) ([]ListDispensersByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listDispensersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDispensersByCustomerRow
	for rows.Next() {
		var i ListDispensersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ZoneID,
			&i.SortOrder,
			&i.SeqLabel,
			&i.Location,
			&i.ModelID,
			&i.Quantity,
			&i.FragranceID,
			&i.FragranceNote,
			&i.RefillSizeMl,
			&i.ServiceIntervalDays,
			&i.Notes,
			&i.Active,
			&i.ModelName,
			&i.FragranceName,
			&i.ZoneLabel,
			&i.ZoneArea,
			&i.ZoneSort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByCustomer = `-- name: ListZonesByCustomer :many

SELECT id, customer_id, sort_order, label, area, access_notes, notes FROM zones WHERE customer_id = ? ORDER BY sort_order, id
`

// Zones -----------------------------------------------------------------
func (q *Queries) ListZonesByCustomer(ctx context.Context, customerID int64) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, listZonesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SortOrder,
			&i.Label,
			&i.Area,
			&i.AccessNotes,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCustomerFromRun = `-- name: RemoveCustomerFromRun :exec
UPDATE customers SET run_id = NULL WHERE id = ?
`

func (q *Queries) RemoveCustomerFromRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCustomerFromRun, id)
	return err
}

const setCustomerSortOrder = `-- name: SetCustomerSortOrder :exec
UPDATE customers SET sort_order = ? WHERE id = ?
`

type SetCustomerSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetCustomerSortOrder(ctx context.Context, arg SetCustomerSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setCustomerSortOrder, arg.SortOrder, arg.ID)
	return err
}

const setDispenserSortOrder = `-- name: SetDispenserSortOrder :exec
UPDATE dispensers SET sort_order = ? WHERE id = ?
`

type SetDispenserSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetDispenserSortOrder(ctx context.Context, arg SetDispenserSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setDispenserSortOrder, arg.SortOrder, arg.ID)
	return err
}

const setZoneSortOrder = `-- name: SetZoneSortOrder :exec
UPDATE zones SET sort_order = ? WHERE id = ?
`

type SetZoneSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetZoneSortOrder(ctx context.Context, arg SetZoneSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setZoneSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :exec
UPDATE contacts SET name = ?, role = ?, is_primary = ?, phone = ?, notes = ? WHERE id = ?
`

type UpdateContactParams struct {
	Name      string `json:"name"`
	Role      string `json:"role"`
	IsPrimary int64  `json:"is_primary"`
	Phone     string `json:"phone"`
	Notes     string `json:"notes"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) error {
	_, err := q.db.ExecContext(ctx, updateContact,
		arg.Name,
		arg.Role,
		arg.IsPrimary,
		arg.Phone,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers SET
    name = ?, address_line = ?, suburb = ?, phone = ?, map_ref = ?,
    regarding = ?, service_minutes = ?, access_notes = ?, general_notes = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Name           string `json:"name"`
	AddressLine    string `json:"address_line"`
	Suburb         string `json:"suburb"`
	Phone          string `json:"phone"`
	MapRef         string `json:"map_ref"`
	Regarding      string `json:"regarding"`
	ServiceMinutes int64  `json:"service_minutes"`
	AccessNotes    string `json:"access_notes"`
	GeneralNotes   string `json:"general_notes"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Name,
		arg.AddressLine,
		arg.Suburb,
		arg.Phone,
		arg.MapRef,
		arg.Regarding,
		arg.ServiceMinutes,
		arg.AccessNotes,
		arg.GeneralNotes,
		arg.ID,
	)
	return err
}

const updateDispenser = `-- name: UpdateDispenser :exec
UPDATE dispensers SET
    zone_id = ?, seq_label = ?, location = ?, model_id = ?, quantity = ?,
    fragrance_id = ?, fragrance_note = ?, refill_size_ml = ?,
    service_interval_days = ?, notes = ?
WHERE id = ?
`

type UpdateDispenserParams struct {
	ZoneID              sql.NullInt64 `json:"zone_id"`
	SeqLabel            string        `json:"seq_label"`
	Location            string        `json:"location"`
	ModelID             int64         `json:"model_id"`
	Quantity            int64         `json:"quantity"`
	FragranceID         sql.NullInt64 `json:"fragrance_id"`
	FragranceNote       string        `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64 `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64 `json:"service_interval_days"`
	Notes               string        `json:"notes"`
	ID                  int64         `json:"id"`
}

func (q *Queries) UpdateDispenser(ctx context.Context, arg UpdateDispenserParams) error {
	_, err := q.db.ExecContext(ctx, updateDispenser,
		arg.ZoneID,
		arg.SeqLabel,
		arg.Location,
		arg.ModelID,
		arg.Quantity,
		arg.FragranceID,
		arg.FragranceNote,
		arg.RefillSizeMl,
		arg.ServiceIntervalDays,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateZone = `-- name: UpdateZone :exec
UPDATE zones SET label = ?, area = ?, access_notes = ?, notes = ? WHERE id = ?
`

type UpdateZoneParams struct {
	Label       string `json:"label"`
	Area        string `json:"area"`
	AccessNotes string `json:"access_notes"`
	Notes       string `json:"notes"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) error {
	_, err := q.db.ExecContext(ctx, updateZone,
		arg.Label,
		arg.Area,
		arg.AccessNotes,
		arg.Notes,
		arg.ID,
	)
	return err
}
