// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package db

import (
	"context"
	"database/sql"
)

const createFragrance = `-- name: CreateFragrance :exec
INSERT INTO fragrances (name, default_size_ml) VALUES (?, ?)
`

type CreateFragranceParams struct {
	Name          string        `json:"name"`
	DefaultSizeMl sql.NullInt64 `json:"default_size_ml"`
}

func (q *Queries) CreateFragrance(ctx context.Context, arg CreateFragranceParams) error {
	_, err := q.db.ExecContext(ctx, createFragrance, arg.Name, arg.DefaultSizeMl)
	return err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO dispenser_models (name) VALUES (?)
`

func (q *Queries) CreateModel(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createModel, name)
	return err
}

const getFragrance = `-- name: GetFragrance :one
SELECT id, name, default_size_ml, active FROM fragrances WHERE id = ?
`

func (q *Queries) GetFragrance(ctx context.Context, id int64) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, getFragrance, id)
	var i Fragrance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultSizeMl,
		&i.Active,
	)
	return i, err
}

const getFragranceByName = `-- name: GetFragranceByName :one
SELECT id, name, default_size_ml, active FROM fragrances WHERE name = ?
`

func (q *Queries) GetFragranceByName(ctx context.Context, name string) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, getFragranceByName, name)
	var i Fragrance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultSizeMl,
		&i.Active,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, name, active FROM dispenser_models WHERE id = ?
`

func (q *Queries) GetModel(ctx context.Context, id int64) (DispenserModel, error) {
	row := q.db.QueryRowContext(ctx, getModel, id)
	var i DispenserModel
	err := row.Scan(&i.ID, &i.Name, &i.Active)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, name, active FROM dispenser_models WHERE name = ?
`

func (q *Queries) GetModelByName(ctx context.Context, name string) (DispenserModel, error) {
	row := q.db.QueryRowContext(ctx, getModelByName, name)
	var i DispenserModel
	err := row.Scan(&i.ID, &i.Name, &i.Active)
	return i, err
}

const listFragrances = `-- name: ListFragrances :many

SELECT id, name, default_size_ml, active FROM fragrances ORDER BY active DESC, name
`

// Fragrances ---------------------------------------------------------------
func (q *Queries) ListFragrances(ctx context.Context) ([]Fragrance, error) {
	rows, err := q.db.QueryContext(ctx, listFragrances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fragrance
	for rows.Next() {
		var i Fragrance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultSizeMl,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many

SELECT id, name, active FROM dispenser_models ORDER BY active DESC, name
`

// Dispenser models --------------------------------------------------------
func (q *Queries) ListModels(ctx context.Context) ([]DispenserModel, error) {
	rows, err := q.db.QueryContext(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispenserModel
	for rows.Next() {
		var i DispenserModel
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFragrances = `-- name: SearchFragrances :many
SELECT id, name, default_size_ml, active FROM fragrances
WHERE active = 1 AND name LIKE ?
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchFragrances(ctx context.Context, name string) ([]Fragrance, error) {
	rows, err := q.db.QueryContext(ctx, searchFragrances, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fragrance
	for rows.Next() {
		var i Fragrance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultSizeMl,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchModels = `-- name: SearchModels :many
SELECT id, name, active FROM dispenser_models
WHERE active = 1 AND name LIKE ?
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchModels(ctx context.Context, name string) ([]DispenserModel, error) {
	rows, err := q.db.QueryContext(ctx, searchModels, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispenserModel
	for rows.Next() {
		var i DispenserModel
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFragrance = `-- name: UpdateFragrance :exec
UPDATE fragrances SET name = ?, default_size_ml = ?, active = ? WHERE id = ?
`

type UpdateFragranceParams struct {
	Name          string        `json:"name"`
	DefaultSizeMl sql.NullInt64 `json:"default_size_ml"`
	Active        int64         `json:"active"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateFragrance(ctx context.Context, arg UpdateFragranceParams) error {
	_, err := q.db.ExecContext(ctx, updateFragrance,
		arg.Name,
		arg.DefaultSizeMl,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateModel = `-- name: UpdateModel :exec
UPDATE dispenser_models SET name = ?, active = ? WHERE id = ?
`

type UpdateModelParams struct {
	Name   string `json:"name"`
	Active int64  `json:"active"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.ExecContext(ctx, updateModel, arg.Name, arg.Active, arg.ID)
	return err
}
