// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ApprovedEmail struct {
	Email       string `json:"email"`
	FranchiseID int64  `json:"franchise_id"`
}

type Contact struct {
	ID         int64  `json:"id"`
	CustomerID int64  `json:"customer_id"`
	Name       string `json:"name"`
	Role       string `json:"role"`
	IsPrimary  int64  `json:"is_primary"`
	Phone      string `json:"phone"`
	Notes      string `json:"notes"`
}

type Customer struct {
	ID             int64         `json:"id"`
	FranchiseID    int64         `json:"franchise_id"`
	RunID          sql.NullInt64 `json:"run_id"`
	SortOrder      int64         `json:"sort_order"`
	Name           string        `json:"name"`
	AddressLine    string        `json:"address_line"`
	Suburb         string        `json:"suburb"`
	Phone          string        `json:"phone"`
	MapRef         string        `json:"map_ref"`
	Regarding      string        `json:"regarding"`
	ServiceMinutes int64         `json:"service_minutes"`
	AccessNotes    string        `json:"access_notes"`
	GeneralNotes   string        `json:"general_notes"`
	Active         int64         `json:"active"`
}

type Dispenser struct {
	ID                  int64         `json:"id"`
	CustomerID          int64         `json:"customer_id"`
	ZoneID              sql.NullInt64 `json:"zone_id"`
	SortOrder           int64         `json:"sort_order"`
	SeqLabel            string        `json:"seq_label"`
	Location            string        `json:"location"`
	ModelID             int64         `json:"model_id"`
	Quantity            int64         `json:"quantity"`
	FragranceID         sql.NullInt64 `json:"fragrance_id"`
	FragranceNote       string        `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64 `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64 `json:"service_interval_days"`
	Notes               string        `json:"notes"`
	Active              int64         `json:"active"`
}

type DispenserModel struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Active int64  `json:"active"`
}

type EmailToken struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	Purpose   string `json:"purpose"`
	ExpiresAt string `json:"expires_at"`
}

type Fragrance struct {
	ID            int64         `json:"id"`
	Name          string        `json:"name"`
	DefaultSizeMl sql.NullInt64 `json:"default_size_ml"`
	Active        int64         `json:"active"`
}

type Franchise struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Active    int64  `json:"active"`
	CreatedAt string `json:"created_at"`
}

type Run struct {
	ID          int64  `json:"id"`
	FranchiseID int64  `json:"franchise_id"`
	Name        string `json:"name"`
	Notes       string `json:"notes"`
	Active      int64  `json:"active"`
	CreatedAt   string `json:"created_at"`
}

type RunSheet struct {
	ID          int64          `json:"id"`
	RunID       int64          `json:"run_id"`
	RunDate     string         `json:"run_date"`
	Status      string         `json:"status"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	Signature   string         `json:"signature"`
	SignedBy    string         `json:"signed_by"`
	SignedAt    sql.NullString `json:"signed_at"`
}

type RunSheetStop struct {
	ID          int64          `json:"id"`
	RunSheetID  int64          `json:"run_sheet_id"`
	CustomerID  int64          `json:"customer_id"`
	SortOrder   int64          `json:"sort_order"`
	Status      string         `json:"status"`
	Note        string         `json:"note"`
	CompletedAt sql.NullString `json:"completed_at"`
	CompletedBy sql.NullInt64  `json:"completed_by"`
}

type RunSheetTick struct {
	ID          int64  `json:"id"`
	RunSheetID  int64  `json:"run_sheet_id"`
	DispenserID int64  `json:"dispenser_id"`
	TickedBy    int64  `json:"ticked_by"`
	TickedAt    string `json:"ticked_at"`
	Note        string `json:"note"`
}

type Session struct {
	ID          string        `json:"id"`
	UserID      int64         `json:"user_id"`
	FranchiseID sql.NullInt64 `json:"franchise_id"`
	ExpiresAt   string        `json:"expires_at"`
}

type User struct {
	ID            int64         `json:"id"`
	Email         string        `json:"email"`
	Name          string        `json:"name"`
	PasswordHash  string        `json:"password_hash"`
	EmailVerified int64         `json:"email_verified"`
	FranchiseID   sql.NullInt64 `json:"franchise_id"`
	IsAdmin       int64         `json:"is_admin"`
	Approved      int64         `json:"approved"`
	CreatedAt     string        `json:"created_at"`
}

type Zone struct {
	ID          int64  `json:"id"`
	CustomerID  int64  `json:"customer_id"`
	SortOrder   int64  `json:"sort_order"`
	Label       string `json:"label"`
	Area        string `json:"area"`
	AccessNotes string `json:"access_notes"`
	Notes       string `json:"notes"`
}
