// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"
)

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (franchise_id, name) VALUES (?, ?)
`

type CreateRunParams struct {
	FranchiseID int64  `json:"franchise_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun, arg.FranchiseID, arg.Name)
	return err
}

const deactivateRun = `-- name: DeactivateRun :exec
UPDATE runs SET active = 0 WHERE id = ?
`

func (q *Queries) DeactivateRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateRun, id)
	return err
}

const getLastRun = `-- name: GetLastRun :one
SELECT id, franchise_id, name, notes, active, created_at FROM runs WHERE id = (SELECT MAX(id) FROM runs)
`

func (q *Queries) GetLastRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLastRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.Name,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, franchise_id, name, notes, active, created_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.Name,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCustomersByFranchise = `-- name: ListActiveCustomersByFranchise :many
SELECT id, franchise_id, run_id, sort_order, name, address_line, suburb, phone, map_ref, regarding, service_minutes, access_notes, general_notes, active FROM customers
WHERE franchise_id = ? AND active = 1
ORDER BY name
`

func (q *Queries) ListActiveCustomersByFranchise(ctx context.Context, franchiseID int64) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCustomersByFranchise, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FranchiseID,
			&i.RunID,
			&i.SortOrder,
			&i.Name,
			&i.AddressLine,
			&i.Suburb,
			&i.Phone,
			&i.MapRef,
			&i.Regarding,
			&i.ServiceMinutes,
			&i.AccessNotes,
			&i.GeneralNotes,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCustomers = `-- name: ListRunCustomers :many
SELECT c.id, c.franchise_id, c.run_id, c.sort_order, c.name, c.address_line, c.suburb, c.phone, c.map_ref, c.regarding, c.service_minutes, c.access_notes, c.general_notes, c.active,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     WHERE d.customer_id = c.id AND d.active = 1) AS unit_count
FROM customers c
WHERE c.run_id = ? AND c.active = 1
ORDER BY c.sort_order, c.id
`

type ListRunCustomersRow struct {
	ID             int64         `json:"id"`
	FranchiseID    int64         `json:"franchise_id"`
	RunID          sql.NullInt64 `json:"run_id"`
	SortOrder      int64         `json:"sort_order"`
	Name           string        `json:"name"`
	AddressLine    string        `json:"address_line"`
	Suburb         string        `json:"suburb"`
	Phone          string        `json:"phone"`
	MapRef         string        `json:"map_ref"`
	Regarding      string        `json:"regarding"`
	ServiceMinutes int64         `json:"service_minutes"`
	AccessNotes    string        `json:"access_notes"`
	GeneralNotes   string        `json:"general_notes"`
	Active         int64         `json:"active"`
	UnitCount      int64         `json:"unit_count"`
}

func (q *Queries) ListRunCustomers(ctx context.Context, runID sql.NullInt64) ([]ListRunCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunCustomers, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunCustomersRow
	for rows.Next() {
		var i ListRunCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.FranchiseID,
			&i.RunID,
			&i.SortOrder,
			&i.Name,
			&i.AddressLine,
			&i.Suburb,
			&i.Phone,
			&i.MapRef,
			&i.Regarding,
			&i.ServiceMinutes,
			&i.AccessNotes,
			&i.GeneralNotes,
			&i.Active,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByFranchise = `-- name: ListRunsByFranchise :many

SELECT r.id, r.franchise_id, r.name, r.notes, r.active, r.created_at,
    (SELECT COUNT(*) FROM customers c WHERE c.run_id = r.id AND c.active = 1) AS stop_count,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     JOIN customers c ON c.id = d.customer_id
     WHERE c.run_id = r.id AND c.active = 1 AND d.active = 1) AS unit_count
FROM runs r
WHERE r.franchise_id = ? AND r.active = 1
ORDER BY r.name
`

type ListRunsByFranchiseRow struct {
	ID          int64  `json:"id"`
	FranchiseID int64  `json:"franchise_id"`
	Name        string `json:"name"`
	Notes       string `json:"notes"`
	Active      int64  `json:"active"`
	CreatedAt   string `json:"created_at"`
	StopCount   int64  `json:"stop_count"`
	UnitCount   int64  `json:"unit_count"`
}

// Runs ------------------------------------------------------------------
func (q *Queries) ListRunsByFranchise(ctx context.Context, franchiseID int64) ([]ListRunsByFranchiseRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByFranchise, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByFranchiseRow
	for rows.Next() {
		var i ListRunsByFranchiseRow
		if err := rows.Scan(
			&i.ID,
			&i.FranchiseID,
			&i.Name,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.StopCount,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedCustomers = `-- name: ListUnassignedCustomers :many
SELECT id, franchise_id, run_id, sort_order, name, address_line, suburb, phone, map_ref, regarding, service_minutes, access_notes, general_notes, active FROM customers
WHERE franchise_id = ? AND active = 1 AND run_id IS NULL
ORDER BY name
`

func (q *Queries) ListUnassignedCustomers(ctx context.Context, franchiseID int64) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedCustomers, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FranchiseID,
			&i.RunID,
			&i.SortOrder,
			&i.Name,
			&i.AddressLine,
			&i.Suburb,
			&i.Phone,
			&i.MapRef,
			&i.Regarding,
			&i.ServiceMinutes,
			&i.AccessNotes,
			&i.GeneralNotes,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :exec
UPDATE runs SET name = ?, notes = ? WHERE id = ?
`

type UpdateRunParams struct {
	Name  string `json:"name"`
	Notes string `json:"notes"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun, arg.Name, arg.Notes, arg.ID)
	return err
}
