// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sheets.sql

package db

import (
	"context"
	"database/sql"
)

const clearRunSheetSignature = `-- name: ClearRunSheetSignature :exec
UPDATE run_sheets SET signature = '', signed_by = '', signed_at = NULL WHERE id = ?
`

func (q *Queries) ClearRunSheetSignature(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearRunSheetSignature, id)
	return err
}

const completeRunSheet = `-- name: CompleteRunSheet :exec
UPDATE run_sheets SET status = 'completed', completed_at = datetime('now') WHERE id = ?
`

func (q *Queries) CompleteRunSheet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeRunSheet, id)
	return err
}

const countPendingStops = `-- name: CountPendingStops :one
SELECT COUNT(*) FROM run_sheet_stops WHERE run_sheet_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingStops(ctx context.Context, runSheetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingStops, runSheetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunSheet = `-- name: CreateRunSheet :exec

INSERT INTO run_sheets (run_id, run_date, created_by) VALUES (?, ?, ?)
`

type CreateRunSheetParams struct {
	RunID     int64  `json:"run_id"`
	RunDate   string `json:"run_date"`
	CreatedBy int64  `json:"created_by"`
}

// Run sheets (an execution of a run on a date) ----------------------------
func (q *Queries) CreateRunSheet(ctx context.Context, arg CreateRunSheetParams) error {
	_, err := q.db.ExecContext(ctx, createRunSheet, arg.RunID, arg.RunDate, arg.CreatedBy)
	return err
}

const createStopsForSheet = `-- name: CreateStopsForSheet :exec

INSERT INTO run_sheet_stops (run_sheet_id, customer_id, sort_order)
SELECT ?, id, sort_order FROM customers WHERE run_id = ? AND active = 1
`

type CreateStopsForSheetParams struct {
	RunSheetID int64         `json:"run_sheet_id"`
	RunID      sql.NullInt64 `json:"run_id"`
}

// Stops -------------------------------------------------------------------
func (q *Queries) CreateStopsForSheet(ctx context.Context, arg CreateStopsForSheetParams) error {
	_, err := q.db.ExecContext(ctx, createStopsForSheet, arg.RunSheetID, arg.RunID)
	return err
}

const createTick = `-- name: CreateTick :exec

INSERT INTO run_sheet_ticks (run_sheet_id, dispenser_id, ticked_by)
VALUES (?, ?, ?)
ON CONFLICT(run_sheet_id, dispenser_id) DO NOTHING
`

type CreateTickParams struct {
	RunSheetID  int64 `json:"run_sheet_id"`
	DispenserID int64 `json:"dispenser_id"`
	TickedBy    int64 `json:"ticked_by"`
}

// Ticks -------------------------------------------------------------------
func (q *Queries) CreateTick(ctx context.Context, arg CreateTickParams) error {
	_, err := q.db.ExecContext(ctx, createTick, arg.RunSheetID, arg.DispenserID, arg.TickedBy)
	return err
}

const deleteTick = `-- name: DeleteTick :exec
DELETE FROM run_sheet_ticks WHERE run_sheet_id = ? AND dispenser_id = ?
`

type DeleteTickParams struct {
	RunSheetID  int64 `json:"run_sheet_id"`
	DispenserID int64 `json:"dispenser_id"`
}

func (q *Queries) DeleteTick(ctx context.Context, arg DeleteTickParams) error {
	_, err := q.db.ExecContext(ctx, deleteTick, arg.RunSheetID, arg.DispenserID)
	return err
}

const getLastRunSheet = `-- name: GetLastRunSheet :one
SELECT id, run_id, run_date, status, created_by, created_at, completed_at, signature, signed_by, signed_at FROM run_sheets WHERE id = (SELECT MAX(id) FROM run_sheets)
`

func (q *Queries) GetLastRunSheet(ctx context.Context) (RunSheet, error) {
	row := q.db.QueryRowContext(ctx, getLastRunSheet)
	var i RunSheet
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Signature,
		&i.SignedBy,
		&i.SignedAt,
	)
	return i, err
}

const getOpenRunSheetForRun = `-- name: GetOpenRunSheetForRun :one
SELECT id, run_id, run_date, status, created_by, created_at, completed_at, signature, signed_by, signed_at FROM run_sheets WHERE run_id = ? AND status = 'open' ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetOpenRunSheetForRun(ctx context.Context, runID int64) (RunSheet, error) {
	row := q.db.QueryRowContext(ctx, getOpenRunSheetForRun, runID)
	var i RunSheet
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Signature,
		&i.SignedBy,
		&i.SignedAt,
	)
	return i, err
}

const getRunSheet = `-- name: GetRunSheet :one
SELECT s.id, s.run_id, s.run_date, s.status, s.created_by, s.created_at, s.completed_at, s.signature, s.signed_by, s.signed_at, r.name AS run_name, r.franchise_id
FROM run_sheets s
JOIN runs r ON r.id = s.run_id
WHERE s.id = ?
`

type GetRunSheetRow struct {
	ID          int64          `json:"id"`
	RunID       int64          `json:"run_id"`
	RunDate     string         `json:"run_date"`
	Status      string         `json:"status"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	Signature   string         `json:"signature"`
	SignedBy    string         `json:"signed_by"`
	SignedAt    sql.NullString `json:"signed_at"`
	RunName     string         `json:"run_name"`
	FranchiseID int64          `json:"franchise_id"`
}

func (q *Queries) GetRunSheet(ctx context.Context, id int64) (GetRunSheetRow, error) {
	row := q.db.QueryRowContext(ctx, getRunSheet, id)
	var i GetRunSheetRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Signature,
		&i.SignedBy,
		&i.SignedAt,
		&i.RunName,
		&i.FranchiseID,
	)
	return i, err
}

const getStop = `-- name: GetStop :one
SELECT st.id, st.run_sheet_id, st.customer_id, st.sort_order, st.status, st.note, st.completed_at, st.completed_by, c.name AS customer_name, c.address_line, c.suburb, c.phone,
    c.map_ref, c.access_notes, c.general_notes, c.service_minutes,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     WHERE d.customer_id = st.customer_id AND d.active = 1) AS total_units,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     JOIN run_sheet_ticks t ON t.dispenser_id = d.id AND t.run_sheet_id = st.run_sheet_id
     WHERE d.customer_id = st.customer_id AND d.active = 1) AS ticked_units
FROM run_sheet_stops st
JOIN customers c ON c.id = st.customer_id
WHERE st.id = ?
`

type GetStopRow struct {
	ID             int64          `json:"id"`
	RunSheetID     int64          `json:"run_sheet_id"`
	CustomerID     int64          `json:"customer_id"`
	SortOrder      int64          `json:"sort_order"`
	Status         string         `json:"status"`
	Note           string         `json:"note"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CompletedBy    sql.NullInt64  `json:"completed_by"`
	CustomerName   string         `json:"customer_name"`
	AddressLine    string         `json:"address_line"`
	Suburb         string         `json:"suburb"`
	Phone          string         `json:"phone"`
	MapRef         string         `json:"map_ref"`
	AccessNotes    string         `json:"access_notes"`
	GeneralNotes   string         `json:"general_notes"`
	ServiceMinutes int64          `json:"service_minutes"`
	TotalUnits     int64          `json:"total_units"`
	TickedUnits    int64          `json:"ticked_units"`
}

func (q *Queries) GetStop(ctx context.Context, id int64) (GetStopRow, error) {
	row := q.db.QueryRowContext(ctx, getStop, id)
	var i GetStopRow
	err := row.Scan(
		&i.ID,
		&i.RunSheetID,
		&i.CustomerID,
		&i.SortOrder,
		&i.Status,
		&i.Note,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CustomerName,
		&i.AddressLine,
		&i.Suburb,
		&i.Phone,
		&i.MapRef,
		&i.AccessNotes,
		&i.GeneralNotes,
		&i.ServiceMinutes,
		&i.TotalUnits,
		&i.TickedUnits,
	)
	return i, err
}

const getStopBySheetAndCustomer = `-- name: GetStopBySheetAndCustomer :one
SELECT id, run_sheet_id, customer_id, sort_order, status, note, completed_at, completed_by FROM run_sheet_stops WHERE run_sheet_id = ? AND customer_id = ?
`

type GetStopBySheetAndCustomerParams struct {
	RunSheetID int64 `json:"run_sheet_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) GetStopBySheetAndCustomer(ctx context.Context, arg GetStopBySheetAndCustomerParams) (RunSheetStop, error) {
	row := q.db.QueryRowContext(ctx, getStopBySheetAndCustomer, arg.RunSheetID, arg.CustomerID)
	var i RunSheetStop
	err := row.Scan(
		&i.ID,
		&i.RunSheetID,
		&i.CustomerID,
		&i.SortOrder,
		&i.Status,
		&i.Note,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const getStopDispenser = `-- name: GetStopDispenser :one
SELECT d.id, d.customer_id, d.zone_id, d.sort_order, d.seq_label, d.location, d.model_id, d.quantity, d.fragrance_id, d.fragrance_note, d.refill_size_ml, d.service_interval_days, d.notes, d.active, m.name AS model_name, f.name AS fragrance_name,
    z.label AS zone_label, z.area AS zone_area, z.access_notes AS zone_access_notes,
    z.sort_order AS zone_sort,
    t.id AS tick_id, t.ticked_at, t.note AS tick_note
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
LEFT JOIN fragrances f ON f.id = d.fragrance_id
LEFT JOIN zones z ON z.id = d.zone_id
LEFT JOIN run_sheet_ticks t ON t.dispenser_id = d.id AND t.run_sheet_id = ?
WHERE d.id = ?
`

type GetStopDispenserParams struct {
	RunSheetID int64 `json:"run_sheet_id"`
	ID         int64 `json:"id"`
}

type GetStopDispenserRow struct {
	ID                  int64          `json:"id"`
	CustomerID          int64          `json:"customer_id"`
	ZoneID              sql.NullInt64  `json:"zone_id"`
	SortOrder           int64          `json:"sort_order"`
	SeqLabel            string         `json:"seq_label"`
	Location            string         `json:"location"`
	ModelID             int64          `json:"model_id"`
	Quantity            int64          `json:"quantity"`
	FragranceID         sql.NullInt64  `json:"fragrance_id"`
	FragranceNote       string         `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64  `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64  `json:"service_interval_days"`
	Notes               string         `json:"notes"`
	Active              int64          `json:"active"`
	ModelName           string         `json:"model_name"`
	FragranceName       sql.NullString `json:"fragrance_name"`
	ZoneLabel           sql.NullString `json:"zone_label"`
	ZoneArea            sql.NullString `json:"zone_area"`
	ZoneAccessNotes     sql.NullString `json:"zone_access_notes"`
	ZoneSort            sql.NullInt64  `json:"zone_sort"`
	TickID              sql.NullInt64  `json:"tick_id"`
	TickedAt            sql.NullString `json:"ticked_at"`
	TickNote            sql.NullString `json:"tick_note"`
}

func (q *Queries) GetStopDispenser(ctx context.Context, arg GetStopDispenserParams) (GetStopDispenserRow, error) {
	row := q.db.QueryRowContext(ctx, getStopDispenser, arg.RunSheetID, arg.ID)
	var i GetStopDispenserRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ZoneID,
		&i.SortOrder,
		&i.SeqLabel,
		&i.Location,
		&i.ModelID,
		&i.Quantity,
		&i.FragranceID,
		&i.FragranceNote,
		&i.RefillSizeMl,
		&i.ServiceIntervalDays,
		&i.Notes,
		&i.Active,
		&i.ModelName,
		&i.FragranceName,
		&i.ZoneLabel,
		&i.ZoneArea,
		&i.ZoneAccessNotes,
		&i.ZoneSort,
		&i.TickID,
		&i.TickedAt,
		&i.TickNote,
	)
	return i, err
}

const getTick = `-- name: GetTick :one
SELECT id, run_sheet_id, dispenser_id, ticked_by, ticked_at, note FROM run_sheet_ticks WHERE run_sheet_id = ? AND dispenser_id = ?
`

type GetTickParams struct {
	RunSheetID  int64 `json:"run_sheet_id"`
	DispenserID int64 `json:"dispenser_id"`
}

func (q *Queries) GetTick(ctx context.Context, arg GetTickParams) (RunSheetTick, error) {
	row := q.db.QueryRowContext(ctx, getTick, arg.RunSheetID, arg.DispenserID)
	var i RunSheetTick
	err := row.Scan(
		&i.ID,
		&i.RunSheetID,
		&i.DispenserID,
		&i.TickedBy,
		&i.TickedAt,
		&i.Note,
	)
	return i, err
}

const listOpenRunSheetsByFranchise = `-- name: ListOpenRunSheetsByFranchise :many
SELECT s.id, s.run_id, s.run_date, s.status, s.created_by, s.created_at, s.completed_at, s.signature, s.signed_by, s.signed_at, r.name AS run_name,
    (SELECT COUNT(*) FROM run_sheet_stops st WHERE st.run_sheet_id = s.id) AS stop_count,
    (SELECT COUNT(*) FROM run_sheet_stops st
     WHERE st.run_sheet_id = s.id AND st.status != 'pending') AS done_count
FROM run_sheets s
JOIN runs r ON r.id = s.run_id
WHERE r.franchise_id = ? AND s.status = 'open'
ORDER BY s.created_at DESC
`

type ListOpenRunSheetsByFranchiseRow struct {
	ID          int64          `json:"id"`
	RunID       int64          `json:"run_id"`
	RunDate     string         `json:"run_date"`
	Status      string         `json:"status"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	Signature   string         `json:"signature"`
	SignedBy    string         `json:"signed_by"`
	SignedAt    sql.NullString `json:"signed_at"`
	RunName     string         `json:"run_name"`
	StopCount   int64          `json:"stop_count"`
	DoneCount   int64          `json:"done_count"`
}

func (q *Queries) ListOpenRunSheetsByFranchise(ctx context.Context, franchiseID int64) ([]ListOpenRunSheetsByFranchiseRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenRunSheetsByFranchise, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenRunSheetsByFranchiseRow
	for rows.Next() {
		var i ListOpenRunSheetsByFranchiseRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RunDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Signature,
			&i.SignedBy,
			&i.SignedAt,
			&i.RunName,
			&i.StopCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCompletedSheets = `-- name: ListRecentCompletedSheets :many
SELECT s.id, s.run_id, s.run_date, s.status, s.created_by, s.created_at, s.completed_at, s.signature, s.signed_by, s.signed_at, r.name AS run_name,
    (SELECT COUNT(*) FROM run_sheet_stops st WHERE st.run_sheet_id = s.id) AS stop_count
FROM run_sheets s
JOIN runs r ON r.id = s.run_id
WHERE r.franchise_id = ? AND s.status = 'completed'
ORDER BY s.completed_at DESC
LIMIT 10
`

type ListRecentCompletedSheetsRow struct {
	ID          int64          `json:"id"`
	RunID       int64          `json:"run_id"`
	RunDate     string         `json:"run_date"`
	Status      string         `json:"status"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	Signature   string         `json:"signature"`
	SignedBy    string         `json:"signed_by"`
	SignedAt    sql.NullString `json:"signed_at"`
	RunName     string         `json:"run_name"`
	StopCount   int64          `json:"stop_count"`
}

func (q *Queries) ListRecentCompletedSheets(ctx context.Context, franchiseID int64) ([]ListRecentCompletedSheetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentCompletedSheets, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCompletedSheetsRow
	for rows.Next() {
		var i ListRecentCompletedSheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RunDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Signature,
			&i.SignedBy,
			&i.SignedAt,
			&i.RunName,
			&i.StopCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStopDispensers = `-- name: ListStopDispensers :many

SELECT d.id, d.customer_id, d.zone_id, d.sort_order, d.seq_label, d.location, d.model_id, d.quantity, d.fragrance_id, d.fragrance_note, d.refill_size_ml, d.service_interval_days, d.notes, d.active, m.name AS model_name, f.name AS fragrance_name,
    z.label AS zone_label, z.area AS zone_area, z.access_notes AS zone_access_notes,
    z.sort_order AS zone_sort,
    t.id AS tick_id, t.ticked_at, t.note AS tick_note
FROM dispensers d
JOIN dispenser_models m ON m.id = d.model_id
LEFT JOIN fragrances f ON f.id = d.fragrance_id
LEFT JOIN zones z ON z.id = d.zone_id
LEFT JOIN run_sheet_ticks t ON t.dispenser_id = d.id AND t.run_sheet_id = ?
WHERE d.customer_id = ? AND d.active = 1
ORDER BY COALESCE(z.sort_order, 999999), d.sort_order, d.id
`

type ListStopDispensersParams struct {
	RunSheetID int64 `json:"run_sheet_id"`
	CustomerID int64 `json:"customer_id"`
}

type ListStopDispensersRow struct {
	ID                  int64          `json:"id"`
	CustomerID          int64          `json:"customer_id"`
	ZoneID              sql.NullInt64  `json:"zone_id"`
	SortOrder           int64          `json:"sort_order"`
	SeqLabel            string         `json:"seq_label"`
	Location            string         `json:"location"`
	ModelID             int64          `json:"model_id"`
	Quantity            int64          `json:"quantity"`
	FragranceID         sql.NullInt64  `json:"fragrance_id"`
	FragranceNote       string         `json:"fragrance_note"`
	RefillSizeMl        sql.NullInt64  `json:"refill_size_ml"`
	ServiceIntervalDays sql.NullInt64  `json:"service_interval_days"`
	Notes               string         `json:"notes"`
	Active              int64          `json:"active"`
	ModelName           string         `json:"model_name"`
	FragranceName       sql.NullString `json:"fragrance_name"`
	ZoneLabel           sql.NullString `json:"zone_label"`
	ZoneArea            sql.NullString `json:"zone_area"`
	ZoneAccessNotes     sql.NullString `json:"zone_access_notes"`
	ZoneSort            sql.NullInt64  `json:"zone_sort"`
	TickID              sql.NullInt64  `json:"tick_id"`
	TickedAt            sql.NullString `json:"ticked_at"`
	TickNote            sql.NullString `json:"tick_note"`
}

// Dispensers with tick state for a stop ------------------------------------
func (q *Queries) ListStopDispensers(ctx context.Context, arg ListStopDispensersParams) ([]ListStopDispensersRow, error) {
	rows, err := q.db.QueryContext(ctx, listStopDispensers, arg.RunSheetID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStopDispensersRow
	for rows.Next() {
		var i ListStopDispensersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ZoneID,
			&i.SortOrder,
			&i.SeqLabel,
			&i.Location,
			&i.ModelID,
			&i.Quantity,
			&i.FragranceID,
			&i.FragranceNote,
			&i.RefillSizeMl,
			&i.ServiceIntervalDays,
			&i.Notes,
			&i.Active,
			&i.ModelName,
			&i.FragranceName,
			&i.ZoneLabel,
			&i.ZoneArea,
			&i.ZoneAccessNotes,
			&i.ZoneSort,
			&i.TickID,
			&i.TickedAt,
			&i.TickNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStops = `-- name: ListStops :many
SELECT st.id, st.run_sheet_id, st.customer_id, st.sort_order, st.status, st.note, st.completed_at, st.completed_by, c.name AS customer_name, c.address_line, c.suburb, c.phone,
    c.map_ref, c.access_notes, c.service_minutes,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     WHERE d.customer_id = st.customer_id AND d.active = 1) AS total_units,
    (SELECT CAST(COALESCE(SUM(d.quantity), 0) AS INTEGER) FROM dispensers d
     JOIN run_sheet_ticks t ON t.dispenser_id = d.id AND t.run_sheet_id = st.run_sheet_id
     WHERE d.customer_id = st.customer_id AND d.active = 1) AS ticked_units
FROM run_sheet_stops st
JOIN customers c ON c.id = st.customer_id
WHERE st.run_sheet_id = ?
ORDER BY st.sort_order, st.id
`

type ListStopsRow struct {
	ID             int64          `json:"id"`
	RunSheetID     int64          `json:"run_sheet_id"`
	CustomerID     int64          `json:"customer_id"`
	SortOrder      int64          `json:"sort_order"`
	Status         string         `json:"status"`
	Note           string         `json:"note"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CompletedBy    sql.NullInt64  `json:"completed_by"`
	CustomerName   string         `json:"customer_name"`
	AddressLine    string         `json:"address_line"`
	Suburb         string         `json:"suburb"`
	Phone          string         `json:"phone"`
	MapRef         string         `json:"map_ref"`
	AccessNotes    string         `json:"access_notes"`
	ServiceMinutes int64          `json:"service_minutes"`
	TotalUnits     int64          `json:"total_units"`
	TickedUnits    int64          `json:"ticked_units"`
}

func (q *Queries) ListStops(ctx context.Context, runSheetID int64) ([]ListStopsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStops, runSheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStopsRow
	for rows.Next() {
		var i ListStopsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunSheetID,
			&i.CustomerID,
			&i.SortOrder,
			&i.Status,
			&i.Note,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.CustomerName,
			&i.AddressLine,
			&i.Suburb,
			&i.Phone,
			&i.MapRef,
			&i.AccessNotes,
			&i.ServiceMinutes,
			&i.TotalUnits,
			&i.TickedUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenRunSheet = `-- name: ReopenRunSheet :exec
UPDATE run_sheets SET status = 'open', completed_at = NULL WHERE id = ?
`

func (q *Queries) ReopenRunSheet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, reopenRunSheet, id)
	return err
}

const reopenStop = `-- name: ReopenStop :exec
UPDATE run_sheet_stops
SET status = 'pending', completed_at = NULL, completed_by = NULL
WHERE id = ?
`

func (q *Queries) ReopenStop(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, reopenStop, id)
	return err
}

const saveRunSheetSignature = `-- name: SaveRunSheetSignature :exec
UPDATE run_sheets SET signature = ?, signed_by = ?, signed_at = datetime('now') WHERE id = ?
`

type SaveRunSheetSignatureParams struct {
	Signature string `json:"signature"`
	SignedBy  string `json:"signed_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) SaveRunSheetSignature(ctx context.Context, arg SaveRunSheetSignatureParams) error {
	_, err := q.db.ExecContext(ctx, saveRunSheetSignature, arg.Signature, arg.SignedBy, arg.ID)
	return err
}

const setStopSortOrder = `-- name: SetStopSortOrder :exec
UPDATE run_sheet_stops SET sort_order = ? WHERE id = ?
`

type SetStopSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetStopSortOrder(ctx context.Context, arg SetStopSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setStopSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateStopNote = `-- name: UpdateStopNote :exec
UPDATE run_sheet_stops SET note = ? WHERE id = ?
`

type UpdateStopNoteParams struct {
	Note string `json:"note"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateStopNote(ctx context.Context, arg UpdateStopNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateStopNote, arg.Note, arg.ID)
	return err
}

const updateStopStatus = `-- name: UpdateStopStatus :exec
UPDATE run_sheet_stops
SET status = ?, note = ?, completed_at = datetime('now'), completed_by = ?
WHERE id = ?
`

type UpdateStopStatusParams struct {
	Status      string        `json:"status"`
	Note        string        `json:"note"`
	CompletedBy sql.NullInt64 `json:"completed_by"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdateStopStatus(ctx context.Context, arg UpdateStopStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStopStatus,
		arg.Status,
		arg.Note,
		arg.CompletedBy,
		arg.ID,
	)
	return err
}

const updateTickNote = `-- name: UpdateTickNote :exec
UPDATE run_sheet_ticks SET note = ? WHERE run_sheet_id = ? AND dispenser_id = ?
`

type UpdateTickNoteParams struct {
	Note        string `json:"note"`
	RunSheetID  int64  `json:"run_sheet_id"`
	DispenserID int64  `json:"dispenser_id"`
}

func (q *Queries) UpdateTickNote(ctx context.Context, arg UpdateTickNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateTickNote, arg.Note, arg.RunSheetID, arg.DispenserID)
	return err
}
